apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gke-lab-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gke-lab-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gke-lab-worker
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gke-lab-worker
