output "network_id" { value = google_compute_network.lab.id }
output "network_name" { value = google_compute_network.lab.name }
output "subnet_id" { value = google_compute_subnetwork.gke.id }
output "subnet_name" { value = google_compute_subnetwork.gke.name }
output "subnet_cidr" { value = google_compute_subnetwork.gke.ip_cidr_range }
output "pods_range_name" { value = "pods" }
output "pods_cidr" { value = var.pods_cidr }
output "services_range_name" { value = "services" }
output "services_cidr" { value = var.services_cidr }
output "private_services_range_name" { value = google_compute_global_address.private_services.name }
output "private_services_cidr" { value = var.private_services_cidr }
output "maximum_cluster_nodes" { value = var.maximum_cluster_nodes }
output "maximum_pods_per_node" { value = var.maximum_pods_per_node }
output "pod_node_capacity" { value = local.pod_node_capacity }
output "nat_enabled" { value = var.enable_nat }
output "nat_router_name" { value = var.enable_nat ? google_compute_router.lab[0].name : null }
output "nat_name" { value = var.enable_nat ? google_compute_router_nat.lab[0].name : null }
output "nat_ip_allocation" { value = var.enable_nat ? google_compute_router_nat.lab[0].nat_ip_allocate_option : null }
